c:
  build:
  - cc -c -o hello.c.o hello.c
  entry: hello_c
  library: c
  output: hello.c.o
  requires: cc
  root: /src
cpp:
  build:
  - c++ -c -o hello.cpp.o hello.cpp
  entry: hello_cpp
  library: stdc++
  output: hello.cpp.o
  requires: cpp
  root: /src
d:
  build: 
  - dmd -c -of=hello.d.o hello.d
  entry: hello_d
  library: phobos2
  output: hello.d.o
  requires: dmd
  root: /src
rust:
  build:
  - cargo build
  entry: hello_rust
  library: dl pthread
  output: rust/target/debug/libhello.a
  requires: cargo
  root: /src/rust