c:
  build: cc -c -o hello.c.o hello.c
  entry: hello_c
  library: c
  output: hello.c.o
  requires: cc
  root: /src
lua:
  build: cc -c -o wrapper.o wrapper.c
  entry: hello_lua
  library: lua
  output: hello.lua.o
  requires: cc
  root: /src/lua